### ISSUE TITLE
Question: does pgvecto.rs support disk-based indices?

### ISSUE THREAD

**Issue by mkornacker** [tensorchord/pgvecto.rs#176]
I apologize in advance if this is already documented somewhere. 'm curious whether pgvecto.rs needs the entire index (or substantial portion thereof) to be memory-resident in order to perform lookups. Any pointers to documentation of the runtime resource requirements would be appreciated.

**Comment by VoVAllen** [comment]
Hi, I saw you asked the same question in pgvector. So pgvector and pgvecto.rs both majorly works on HNSW now. HNSW is designed for memory,  but both pgvector and pgvecto.rs implement memory management to allow swapping data to disk when there is insufficient memory. However, the performance will degrade significantly if swapping occurs because HNSW is not designed for it.

To address this issue, the algorithms should be designed to minimize IO on disk, for example, using DiskANN or SPANN, which are currently not implemented.

**Comment by gaocegege** [comment]
I am closing this since we get this: https://github.com/tensorchord/pgvecto.rs/issues/24
