### ISSUE TITLE
feat(docs): VBASE documentation

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#188]
Hi! I noticed you recently added support for VBASE. I'd like to learn a bit more about the use-case for this. I see that it's mutually exclusive with pre-filtering. Does it fulfill a similar purpose? When would I prefer one or the other?

And from skimming the VBASE paper, it seems that part of the algorithm uses a distance-based range filter. Is there a way to optimize range-based queries using this, i.e. for queries where we want to find all the vectors within a certain distance? 

The current approach we have is [here](https://github.com/immich-app/immich/blob/0aae9696f68b830d918780d9c3ffca74352adea9/server/src/infra/repositories/smart-info.repository.ts#L85), where we do pre-filtering on a number of conditions and then do post-filtering on the max distance. If we put the max distance condition in the pre-filtering stage, there's a big performance penalty. But if we apply it through post-filtering, we don't necessarily return all of the rows within that distance, just those within the top k. Would VBASE help with this?

And as always, thank you for working on this project! We made our first release with pgvecto.rs and the rollout has been relatively smooth. The issues relating to pgvecto.rs were mainly because some users used the `latest` docker tag instead of a proper release version.

**Comment by VoVAllen** [comment]
Hi,

VBASE is also used to solve problems like https://github.com/pgvector/pgvector/issues/259. Since the condition is unknown inside the vector search process, it's hard to decide the size of the candidate set (ef_search) which is provided to postgres. VBASE proposes a method, saying all the points in the second phase (relaxed monotonicity) can be returned to postgres. Therefore the returned set becomes an iterator instead of a fixed set.

![image](https://github.com/tensorchord/pgvecto.rs/assets/8686776/f0afead4-ec05-4ee8-9860-9ed006add6b1)

The original method will iterate all the points in this figure, and select the top k points, and return to postgres. However k is hard to decide beforehand with filter conditions. VBASE will start to return the top points when reaching the phase two, so the iteration termination is decided by postgres, when it have enough candidates for `LIMIT k` clause. 

The downside of VBASE is the results no longer strictly monotonous. If user need strict monotonicity, they need to do another order by to force the order.

**Comment by VoVAllen** [comment]
I think vbase fits your scenario very well. Have you tried it?

**Comment by mertalev** [comment]
Thank you for the explanation! I haven't tried VBASE yet, but it sounds ideal for our use. I'll do some testing with it.
