### ISSUE TITLE
feat: Compatibility with pgvector

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#227]
Support pgvector syntax out of the box

**Comment by kemingy** [comment]
## Differences

| Type | `pgvector` | `pgvecto.rs` |
|--------|--------|--------|
| `<->` | L2 | Squared L2 |
| `<=>` | 1-cos | -cos |
| USING  | ivfflat/hnsw | vectors |
| operator | vector_ip_ops/vector_cosine_ops | vector_dot_ops/vector_cos_ops | 
| WITH | directly | `IndexOptions` toml |

I think the cosine distance should be `1-cos` instead of `cos`. Other differences look good to me. At least the pgvecto.rs indexing configuration looks better than pgvector.

**Comment by cutecutecat** [comment]
After #256 , there is still a bit difference at Gucs, including:
- `hnsw.ef_search` at pgvector vs `vectors.hnsw_ef_search` at pgvecto.rs
- `ivfflat.probes` at pgvector vs `vectors.ivf_nporbe` at pgvecto.rs
