### ISSUE TITLE
improvement: Separation of backend services 

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#307]
Separate backend services into independent component with clear interface.

**Comment by cutecutecat** [comment]
# Step 1 -- Mock Worker

## Worker module

```mermaid
graph LR
1[fn session]-->2[Worker]
2[Worker]-->3[WorkerProtect]
2[Worker]-->4[WorkerView]
3[WorkerProtect]-->5[WorkerStartup]
5[WorkerStartup] --> 6[(Handle)]
3[WorkerProtect]-->6[(Handle)]
3[WorkerProtect]-->7[(Instance)]
4[WorkerView]-->6[(Handle)]
4[WorkerView]-->7[(Instance)]
```

### mock struct

- mock a struct needs namespace switch, introduce `mockall_double` crate
- `Worker` is standalone, not mock
- `WorkerProtect` by `mockall.automock`
- `WorkerView` is opaque, not mock

### external dependency

- `std::fs` at `Worker`, introduce `tempfile` crate for a temporary directory
- `Instance` need to mock
- `Handler` is opaque, not mock

## Instance module

```mermaid
graph LR
1[Instance]-->2[(Index)]
3[InstanceView]-->4[(IndexView)]
```



### mock struct

- `Instance` by `mock!` due to `#[derive(Clone)]`
- `InstanceView` by `mock!` due to generic lifetime at return

### external dependency

- `Index` and `IndexView`
