### ISSUE TITLE
Unexpected behavior with NULL

### ISSUE THREAD

**Issue by ergo70** [tensorchord/pgvecto.rs#427]
Hello again,

I noticed some unexpected behavior with NULL values.

```
CREATE TABLE items (                                                                                             id int4 GENERATED BY DEFAULT AS IDENTITY,
embedding vector(1536) NULL,
payload text NULL
);

insert into items (id, embedding, payload) select id, embedding::vector, 'Blahfasel' from items_plain limit 100000;

CREATE INDEX on items USING vectors (embedding vector_cos_ops) WITH (options = $$
[indexing.hnsw]
$$);

ALTER TABLE items ADD PRIMARY KEY (id);

create index on items(payload);

update items set embedding = NULL where id = 100;

select * from items where embedding is null;
 id  | embedding |  payload
-----+-----------+-----------
 100 | <null>    | Blahfasel
(1 row)

SELECT id, embedding <=> NULL AS _score FROM items ORDER BY _score LIMIT 2;
 id | _score
----+--------
  0 | <null>
  1 | <null>
(2 rows)

SELECT id, embedding <=> (select embedding from items where id=100) AS _score FROM items ORDER BY _score LIMIT 2;
ERROR:  Scan failed.
```

NULL returned from a subquery causes an ERROR, while the NULL literal in the same query works.

```
SELECT id, embedding <=> NULL AS _score FROM items ORDER BY _score LIMIT 102;

 id  | _score
-----+--------
   0 | <null>
   1 | <null>
   2 | <null>
   3 | <null>
   4 | <null>
   5 | <null>
   6 | <null>
   7 | <null>
...
  98 | <null>
  99 | <null>
 101 | <null>
 102 | <null>
(102 rows)
```
No ERROR anymore. But: Where is row 100?

Both queries seem to work as expected when I also order by id.

`SELECT id, embedding <=> (select embedding from items where id=100) AS _score FROM items ORDER BY id, _score LIMIT 102;`

best regards,

Ernst-Georg

**Comment by usamoi** [comment]
> NULL returned from a subquery causes an ERROR, while the NULL literal in the same query works.

PostgreSQL knows, if an operand is `NULL`, the result give by operator must be `NULL`. So if there is a `NULL` literal in the query, the index scan is not performed and PostgreSQL returns `NULL` directly.

> No ERROR anymore. But: Where is row 100?

You want `102` rows and PostgreSQL returns `102` rows, so it's expected behavior in PostgreSQL. PostgreSQL takes advantages of "heap tables": all rows are stored unorderedly. It's different from MySQL: in MySQL, all rows are stored in a B-Tree orderedly.

So after you insert many rows, the heap table is like this:

```
[Page 1: (id = 0) (id = 1) (id = 2)]
[Page 2: (id = 3) (id = 4) (id = 5)]
...
[Page 34: (id = 99) (id = 100) (id = 101)]
...
[Page 300: (id = 897) (id = 898)]
```

After you a row, the heap table is like this:

```
[Page 1: (id = 0) (id = 1) (id = 2)]
[Page 2: (id = 3) (id = 4) (id = 5)]
...
[Page 34: (id = 99) (id = 100, but it's invisible because it's deleted) (id = 101)]
...
[Page 300: (id = 897) (id = 898) (id = 100, it's latest version of this row and visible for new transactions)]
```

Now you want 102 rows. PostgreSQL scans for first 35 pages and returns 102 rows.

> Both queries seem to work as expected when I also order by id.

You want 102 ordered rows, so PostgreSQL performs an index scan, instead of a full-table scan. So you get the result you want.

There is a thing `pgvecto.rs` does wrong: `pgvecto.rs` should not throw an error when users give a `NULL` operand to the vector operator. We should change the behavior later.
