### ISSUE TITLE
bug: possible deadlock in 0.3.0-alpha.2

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#495]
> Just to calibrate expectations, how long should building an index for 1.5M vectors take? I tried running with custom options for m and ef_construction - and then quit as it took over 2.5 hours. Also tried the standard command from the docs using the default configuration, but it seems to take > 45 mins, which smells wrong.

source: https://discord.com/channels/974584200327991326/1245115744224542770/1247287333556977695

**Comment by cutecutecat** [comment]
# Experiment 1: Insert random data

| dim  | amount | index build time |
| ---- | ------ | ---------------- |
| 3    | 1.5M   | 517s             |
| 10   | 1.5M   | 1125s            |
| 30   | 1.5M   | 2974s            |
| 100  | 1.5M   | 3225s            |
| 300  | 1.5M   | 5749s            |

# Experiment 2: Insert special data

| dim  | data                                               | index build time |
| ---- | -------------------------------------------------- | ---------------- |
| 3    | 1M random + 0.5 NULL array = `[NULL, ...]::vector` |                  |
| 3    | 1M random + 0.5 inf array = `[inf, ...]::vector`   |                  |
| 3    | 1M random + 0.5 NULL = `NULL::vector`              |                  |

**Comment by rsomani95** [comment]
I'd originally shared the message referenced in the issue description above.

I have since realised that this issue is not caused for smaller datasets. Here is the script I am using to build the dataset:
https://gist.github.com/rsomani95/56194e33364208019a09846cb9bacabb#file-build_dataset_with_indexes-sql

This script runs successfully with these params:
```sql
SET app.num_collections           TO 30;
SET app.num_assets_per_collection TO 50;
SET app.num_segments_per_asset    TO 300;
```
... Creating a table of `(300 * 50 * 30) = 450,000` embeddings.


However, when I change them to:
```sql
SET app.num_collections           TO 10;
SET app.num_assets_per_collection TO 100;
SET app.num_segments_per_asset    TO 1500;
```
it creates a table of `(1500 * 100 * 10) = 1,500,000` embeddings, and then the index building gets stuck at the last line `CREATE INDEX ON segment USING vectors (embedding vector_cos_ops);`

---

This is how I'm launching my docker container:
```bash
docker run \
  --name pgvecto-rs-demo \
  --shm-size 24g \   # In case we need this to mess with memory settings later
  -e POSTGRES_PASSWORD=mysecretpassword \
  -p 4000:5432 \
  -d tensorchord/pgvecto-rs:pg16-v0.3.0-alpha.2
```

**Comment by cutecutecat** [comment]
Target case:
- optiming_thread: From sqrt(cores) at `alpha1` to 1 at `alpha2`
- ...?

**Comment by VoVAllen** [comment]
@rsomani95 Thanks for reporting. We're actively investigate the issue

**Comment by VoVAllen** [comment]
Confirmed it's not a bug. Tune the `optimizing_threads` to larger values solves the issue
