### ISSUE TITLE
research: compatibility with citus

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#577]
Research if we could support citus

**Comment by gaocegege** [comment]
cc @cho-thinkfree-com

**Comment by shetao2015** [comment]
+1

**Comment by cutecutecat** [comment]
# Stream replication

## Current situation
The main problem is at building the index, when index is `replayed` inside PG of `standby instance`:
```
postgres=# select * from pg_indexes where tablename = 't';
 schemaname | tablename | indexname | tablespace |                                               indexdef                                                
------------+-----------+-----------+------------+-------------------------------------------------------------------------------------------------------
 public     | t         | t_val_idx |            | CREATE INDEX t_val_idx ON public.t USING vectors (val vector_l2_ops) WITH (options='[indexing.hnsw]')
(1 row)
```
but the backend hook `ambuild` is not triggered at WAL replay of `standby instance`. So they are no longer in sync, which lead to this error at any vector query:
```
postgres=# SELECT idx_status, idx_indexing FROM pg_vector_index_stat;
ERROR:  pgvecto.rs: The index is not existing in the background worker.
ADVICE: Drop or rebuild the index.
```

## Implement
We need to write a [custom WAL manager](https://paquier.xyz/postgresql-2/postgres-15-custom-rmgr/) like this [PR](https://github.com/paradedb/paradedb/pull/1077).

These operations should be logged:
- Index create
- Index edit
- Index drop

## Limitation
- Write-ahead log (WAL) is supported only on Postgres 15+ due to the fact that custom WAL managers were introduced in Postgres 15

**Comment by cutecutecat** [comment]
# Citus
TODO

**Comment by gaocegege** [comment]
Thanks for your research!
